// Modo demo: categorías y productos de «Modelia BBDD.sql», en el formato de la base de datos.
// Generado automáticamente. Los usuarios y pedidos de la demo son ficticios (ver demo_api.dart).
// ignore_for_file: lines_longer_than_80_chars

const demoCategoriasJson = r'''[
 {
  "id": 1,
  "nombre": "Electrónica",
  "descripcion": "Dispositivos y accesorios electrónicos",
  "imagenUrl": null,
  "activo": true
 },
 {
  "id": 2,
  "nombre": "Hogar",
  "descripcion": "Muebles y decoración para el hogar",
  "imagenUrl": null,
  "activo": true
 },
 {
  "id": 3,
  "nombre": "Ropa",
  "descripcion": "Moda y accesorios",
  "imagenUrl": null,
  "activo": true
 },
 {
  "id": 5,
  "nombre": "Calzado",
  "descripcion": "Zapatillas y Zapatos",
  "imagenUrl": null,
  "activo": true
 },
 {
  "id": 9,
  "nombre": "Deporte",
  "descripcion": "Accesorios de deporte",
  "imagenUrl": null,
  "activo": true
 }
]''';

const demoProductosJson = r'''[
 {
  "id": 1,
  "categoriaId": 1,
  "nombre": "Auriculares Bluetooth Pro",
  "descripcion": "Auriculares inalámbricos con cancelación de ruido activa, 30h de batería y sonido Hi-Fi. Perfectos para trabajo y viajes.",
  "precio": 500.0,
  "stock": 22,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 2,
  "categoriaId": 1,
  "nombre": "Altavoz Portátil 360",
  "descripcion": "Altavoz Bluetooth resistente al agua IPX7, sonido envolvente 360 grados y 20 horas de autonomía.",
  "precio": 59.99,
  "stock": 6,
  "stockMinimo": 3,
  "imagenUrl": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 3,
  "categoriaId": 1,
  "nombre": "Smartwatch Serie X",
  "descripcion": "Reloj inteligente con monitor de salud, GPS integrado, pantalla AMOLED y resistencia al agua 5ATM.",
  "precio": 149.99,
  "stock": 7,
  "stockMinimo": 3,
  "imagenUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 4,
  "categoriaId": 1,
  "nombre": "Teclado Mecánico RGB",
  "descripcion": "Teclado mecánico con switches táctiles, iluminación RGB por tecla y conexión USB-C. Ideal para gaming y programación.",
  "precio": 79.99,
  "stock": 14,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1619683322755-4545503f1afa?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 5,
  "categoriaId": 1,
  "nombre": "Cargador Inalámbrico 15W",
  "descripcion": "Cargador rápido inalámbrico compatible con Qi. Carga tu dispositivo sin cables en cualquier superficie plana.",
  "precio": 29.99,
  "stock": 39,
  "stockMinimo": 8,
  "imagenUrl": "https://images.unsplash.com/photo-1633381638729-27f730955c23?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 6,
  "categoriaId": 2,
  "nombre": "Lámpara de Escritorio LED",
  "descripcion": "Lámpara con 5 niveles de brillo, luz cálida y fría, carga USB integrada y diseño minimalista.",
  "precio": 34.99,
  "stock": 30,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1766411503480-d3b0df6ef198?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 7,
  "categoriaId": 2,
  "nombre": "Silla Ergonómica Home Office",
  "descripcion": "Silla de trabajo con soporte lumbar ajustable, reposabrazos 4D, asiento de espuma viscoelástica y base giratoria.",
  "precio": 299.99,
  "stock": 8,
  "stockMinimo": 2,
  "imagenUrl": "https://images.unsplash.com/photo-1688578735352-9a6f2ac3b70a?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 8,
  "categoriaId": 2,
  "nombre": "Organizador de Escritorio",
  "descripcion": "Organizador modular de bambú con compartimentos para bolígrafos, móvil, notas y accesorios de escritorio.",
  "precio": 24.99,
  "stock": 35,
  "stockMinimo": 8,
  "imagenUrl": "https://images.unsplash.com/photo-1661493818626-629b09c2f4d2?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 9,
  "categoriaId": 2,
  "nombre": "Cafetera Express Automática",
  "descripcion": "Cafetera con molinillo integrado, pantalla táctil, 15 bares de presión y depósito de agua de 1.8 litros.",
  "precio": 189.99,
  "stock": 10,
  "stockMinimo": 2,
  "imagenUrl": "https://images.unsplash.com/photo-1616035596458-2338800a1ff2?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 10,
  "categoriaId": 2,
  "nombre": "Difusor de Aromas Ultrasónico",
  "descripcion": "Difusor de aceites esenciales con luz ambiental RGB, temporizador programable y silencio total de funcionamiento.",
  "precio": 39.99,
  "stock": 22,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1625479968533-de325eb299a4?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 11,
  "categoriaId": 3,
  "nombre": "Camiseta Oversize Premium",
  "descripcion": "Camiseta de algodón 100% orgánico, corte oversize, disponible en 8 colores. Lavado a máquina hasta 40 grados.",
  "precio": 24.99,
  "stock": 50,
  "stockMinimo": 10,
  "imagenUrl": "https://images.unsplash.com/photo-1760998209708-5fc89d7983c0?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 12,
  "categoriaId": 3,
  "nombre": "Sudadera con Capucha Técnica",
  "descripcion": "Sudadera de tejido reciclado con bolsillo canguro, capucha ajustable y costuras planas para mayor comodidad.",
  "precio": 54.99,
  "stock": 30,
  "stockMinimo": 6,
  "imagenUrl": "https://images.unsplash.com/photo-1685354218016-3899c9ef79ad?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 13,
  "categoriaId": 5,
  "nombre": "Zapatillas Running Ultralight",
  "descripcion": "Zapatillas de running con suela de goma natural, plantilla memory foam y upper de tejido transpirable.",
  "precio": 99.99,
  "stock": 15,
  "stockMinimo": 4,
  "imagenUrl": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/calzado/trekking/trekking.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 14,
  "categoriaId": 3,
  "nombre": "Mochila Urban 25L",
  "descripcion": "Mochila urbana impermeable con compartimento para portátil 15\", puerto USB externo y sistema anti-robo.",
  "precio": 69.99,
  "stock": 20,
  "stockMinimo": 4,
  "imagenUrl": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 15,
  "categoriaId": 3,
  "nombre": "Gorra Snapback Ajustable",
  "descripcion": "Gorra de algodón pesado con cierre snapback, visera plana y bordado en relieve. Talla única ajustable.",
  "precio": 19.99,
  "stock": 45,
  "stockMinimo": 10,
  "imagenUrl": "https://images.unsplash.com/photo-1534215754734-18e55d13e346?w=400",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-03-29T18:27:53",
  "destacado": false
 },
 {
  "id": 16,
  "categoriaId": 1,
  "nombre": "Robot Expresivo",
  "descripcion": "Modelo de demostración con animaciones. Prueba las funciones de AR y rotación 3D.",
  "precio": 999.99,
  "stock": 0,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/RobotExpressive.glb",
  "activo": true,
  "createdAt": "2026-04-07T17:51:18",
  "destacado": false
 },
 {
  "id": 17,
  "categoriaId": 1,
  "nombre": "Traje espacial Neil Armstrong",
  "descripcion": "El primero en pisar la Luna el 20 de julio de 1969, con 21 capas de protección, polvo lunar auténtico y sellos de la NASA.  Hecho a mano por costureras de Playtex con teflón y tela Beta ignífuga, resistente a más de 1.000 °F.  Presenta deterioro histórico, manchas de origen desconocido y remiendos, lo que aumenta su valor como pieza única.  Incluye documentación de autenticidad y certificado del Smithsonian.",
  "precio": 9999.0,
  "stock": 1,
  "stockMinimo": 1,
  "imagenUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/neilArmstrong.png",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-07T17:53:04",
  "destacado": false
 },
 {
  "id": 19,
  "categoriaId": 1,
  "nombre": "Maxell Retro DJ Headphones",
  "descripcion": "Los auriculares retro para DJ se inspiraron en una época pasada, pero todos los aspectos de la tecnología moderna se incluyeron en ellos, lo que hizo posible crear un gran producto.",
  "precio": 250.0,
  "stock": 10,
  "stockMinimo": 5,
  "imagenUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/maxell/maxell.png",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/maxell/maxel.glb",
  "activo": true,
  "createdAt": "2026-04-11T12:33:09",
  "destacado": true
 },
 {
  "id": 20,
  "categoriaId": 1,
  "nombre": "eurig K-Slim",
  "descripcion": "Cafetera en cápsulas K-Cup Keurig K-Slim de una sola porción, con 3 tamaños de preparación, tecnología Multistream, depósito extraíble de 46 oz",
  "precio": 499.0,
  "stock": 20,
  "stockMinimo": 5,
  "imagenUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/cafetera/cafetera.png",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/cafetera/cafetera.glb",
  "activo": true,
  "createdAt": "2026-04-11T12:37:19",
  "destacado": true
 },
 {
  "id": 21,
  "categoriaId": 1,
  "nombre": "iPhone 17 pro max",
  "descripcion": "El iPhone 17 Pro y el iPhone 17 Pro Max llegan pisando fuerte con un rediseño total desde la propia base. Su nueva estructura Unibody de aluminio forjado térmicamente eleva la resistencia, el rendimiento y la autonomía a una nueva dimensión. Todo un hito de la ingeniería para crear los modelos de iPhone más potentes de la historia.",
  "precio": 1350.0,
  "stock": 50,
  "stockMinimo": 5,
  "imagenUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/iphone/iphone.png",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/iphone/iphone.glb",
  "activo": true,
  "createdAt": "2026-04-17T12:39:51",
  "destacado": true
 },
 {
  "id": 22,
  "categoriaId": 1,
  "nombre": "Patinete Electrico Xiaomi Mi Electric Scooter M365 Blanco Eu",
  "descripcion": "El M365 es el clásico patinete eléctrico de 8.5 pulgadas",
  "precio": 299.0,
  "stock": 10,
  "stockMinimo": 5,
  "imagenUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/patinete/patinete.png",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/patinete/patinete.glb",
  "activo": true,
  "createdAt": "2026-04-16T12:41:47",
  "destacado": true
 },
 {
  "id": 23,
  "categoriaId": 1,
  "nombre": "Roland TR-808 Rhythm Composer",
  "descripcion": "Instrumento musical electrónico famoso por sus sonidos de síntesis analógica, no basados en muestras reales.",
  "precio": 6000.0,
  "stock": 15,
  "stockMinimo": 5,
  "imagenUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/roland/roland.png",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/roland/roland.glb",
  "activo": true,
  "createdAt": "2026-04-11T12:44:17",
  "destacado": true
 },
 {
  "id": 24,
  "categoriaId": 1,
  "nombre": "Sony α7 II",
  "descripcion": "Cuenta con un sensor full-frame de 24.2 megapíxeles y un sistema de enfoque automático con 693 puntos.",
  "precio": 1863.0,
  "stock": 5,
  "stockMinimo": 1,
  "imagenUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/sony/sony.png",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/electronica/sony/sony.glb",
  "activo": true,
  "createdAt": "2026-04-11T12:45:58",
  "destacado": true
 },
 {
  "id": 25,
  "categoriaId": 2,
  "nombre": "HON Ignition 2.0.",
  "descripcion": "HON Ignition 2.0 Ergonómico Estilo de Malla Abierta con Lumbar Ajustable, Reclinación con Inclinación Sincronizada, Silla de Escritorio para Computadora de Oficina en Casa para Silla de Dolor, Metal de Resina, Azul Hamilton Carolina, Respaldo ReActiv",
  "precio": 1200.0,
  "stock": 30,
  "stockMinimo": 5,
  "imagenUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/hogar/silla/silla.png",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/hogar/silla/silla.glb",
  "activo": true,
  "createdAt": "2026-04-11T12:48:26",
  "destacado": true
 },
 {
  "id": 176,
  "categoriaId": 1,
  "nombre": "Sony WH-1000XM5",
  "descripcion": "Auriculares inalámbricos con cancelación de ruido líder. 30h batería, audio Hi-Res.",
  "precio": 349.99,
  "stock": 15,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 177,
  "categoriaId": 1,
  "nombre": "Apple AirPods Pro 2ª Gen",
  "descripcion": "Cancelación activa de ruido con chip H2. Audio espacial personalizado, 6h escucha.",
  "precio": 279.0,
  "stock": 22,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 178,
  "categoriaId": 1,
  "nombre": "Samsung Galaxy Watch 6",
  "descripcion": "Smartwatch con GPS integrado, monitor de salud avanzado y pantalla AMOLED 1.5\".",
  "precio": 299.99,
  "stock": 18,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 179,
  "categoriaId": 1,
  "nombre": "Keychron K2 Mecánico",
  "descripcion": "Teclado mecánico 75% con retroiluminación RGB. Compatible Windows y Mac.",
  "precio": 89.99,
  "stock": 30,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 180,
  "categoriaId": 1,
  "nombre": "Logitech MX Master 3S",
  "descripcion": "Ratón inalámbrico 8000 DPI, rueda MagSpeed electromagnética. Hasta 70 días batería.",
  "precio": 99.99,
  "stock": 25,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 181,
  "categoriaId": 1,
  "nombre": "iPad Air 5ª Generación",
  "descripcion": "Chip M1, pantalla Liquid Retina 10.9\", compatible con Apple Pencil 2ª gen.",
  "precio": 749.0,
  "stock": 10,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 182,
  "categoriaId": 1,
  "nombre": "MacBook Air M2",
  "descripcion": "Chip M2, pantalla Liquid Retina 13.6\", 18h batería, diseño ultradelgado.",
  "precio": 1299.0,
  "stock": 8,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 183,
  "categoriaId": 1,
  "nombre": "Bose QuietComfort 45",
  "descripcion": "Auriculares over-ear con cancelación de ruido adaptativa. 24h batería.",
  "precio": 279.0,
  "stock": 12,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 184,
  "categoriaId": 1,
  "nombre": "GoPro Hero 12",
  "descripcion": "Cámara de acción 5.3K, estabilización HyperSmooth 6.0, resistente al agua 10m.",
  "precio": 399.99,
  "stock": 14,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 185,
  "categoriaId": 1,
  "nombre": "Amazon Echo Dot 5ª Gen",
  "descripcion": "Altavoz inteligente con Alexa. Sonido mejorado, temperatura ambiente integrada.",
  "precio": 54.99,
  "stock": 40,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1543512214-318c7553f230?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 186,
  "categoriaId": 5,
  "nombre": "Nike Air Max 270",
  "descripcion": "Unidad Air más grande de Nike en el talón. Amortiguación excepcional todo el día.",
  "precio": 149.99,
  "stock": 40,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 187,
  "categoriaId": 5,
  "nombre": "Adidas Ultraboost 23",
  "descripcion": "Entresuela BOOST + Primeknit. La zapatilla de running más cómoda de Adidas.",
  "precio": 179.99,
  "stock": 28,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 188,
  "categoriaId": 5,
  "nombre": "New Balance 574",
  "descripcion": "Icónica zapatilla lifestyle. Entresuela ENCAP para soporte y amortiguación duradera.",
  "precio": 99.0,
  "stock": 35,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 189,
  "categoriaId": 5,
  "nombre": "Converse Chuck Taylor All Star",
  "descripcion": "El clásico atemporal. Lona resistente, suela de goma vulcanizada.",
  "precio": 69.99,
  "stock": 50,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1607522370275-f6fd0a873a6c?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 190,
  "categoriaId": 5,
  "nombre": "Vans Old Skool",
  "descripcion": "Zapatilla icónica con franja lateral DJing. Exterior en ante y lona.",
  "precio": 79.99,
  "stock": 45,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 191,
  "categoriaId": 5,
  "nombre": "Nike Air Force 1",
  "descripcion": "El diseño icónico de baloncesto desde 1982. Cuero limpio, suela Air.",
  "precio": 109.99,
  "stock": 38,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 192,
  "categoriaId": 5,
  "nombre": "Salomon Speedcross 6",
  "descripcion": "Trail running de alta precisión. Suela Contagrip, drop 10mm, agarre en barro.",
  "precio": 139.99,
  "stock": 20,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 193,
  "categoriaId": 5,
  "nombre": "Birkenstock Arizona",
  "descripcion": "Sandalia con plantilla de corcho moldeada anatómicamente. Tiras de cuero.",
  "precio": 89.99,
  "stock": 25,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 194,
  "categoriaId": 5,
  "nombre": "Timberland Premium 6\"",
  "descripcion": "Bota waterproof con suela antideslizante. Icónica desde 1973.",
  "precio": 189.99,
  "stock": 16,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 195,
  "categoriaId": 5,
  "nombre": "Puma Suede Classic",
  "descripcion": "Suede de cuero y suela de goma. Diseño atemporal desde los 60.",
  "precio": 74.99,
  "stock": 30,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 196,
  "categoriaId": 3,
  "nombre": "Gafas Ray-Ban Aviator Classic",
  "descripcion": "Montura dorada con cristales G-15. Protección UV400. Diseño desde 1937.",
  "precio": 169.0,
  "stock": 12,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 197,
  "categoriaId": 3,
  "nombre": "The North Face Resolve Jacket",
  "descripcion": "Chaqueta impermeable HyVent con costuras selladas. Comprimible para viaje.",
  "precio": 129.99,
  "stock": 20,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 198,
  "categoriaId": 3,
  "nombre": "Levi's 501 Original",
  "descripcion": "El jean original desde 1873. Corte recto, botones metálicos, índigo clásico.",
  "precio": 89.99,
  "stock": 35,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 199,
  "categoriaId": 3,
  "nombre": "Canada Goose Expedition Parka",
  "descripcion": "Parka para condiciones extremas (-40°C). Relleno de plumón 625 fill power.",
  "precio": 995.0,
  "stock": 5,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1544923246-77307dd654cb?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 200,
  "categoriaId": 3,
  "nombre": "Carhartt WIP Chase Hoodie",
  "descripcion": "Sudadera de algodón 297g con capucha. Bordado pequeño en el pecho.",
  "precio": 89.99,
  "stock": 28,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 201,
  "categoriaId": 3,
  "nombre": "Swatch Big Bold Chronograph",
  "descripcion": "Reloj de 47mm con correa de bio-material. Movimiento Swissmatic automático.",
  "precio": 249.0,
  "stock": 10,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 202,
  "categoriaId": 3,
  "nombre": "Fular de Cachemira 100%",
  "descripcion": "Fular de cachemira puro, tejido en Nepal. Suave, ligero, 180x70cm.",
  "precio": 129.0,
  "stock": 18,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 203,
  "categoriaId": 3,
  "nombre": "Mochila Herschel Little America",
  "descripcion": "Mochila 30L con cierre de correa. Interior acolchado para portátil 15\".",
  "precio": 109.99,
  "stock": 22,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 204,
  "categoriaId": 3,
  "nombre": "Polo Ralph Lauren Classic Fit",
  "descripcion": "Polo de piqué de algodón con emblema del jinete bordado. Corte clásico.",
  "precio": 89.0,
  "stock": 40,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 205,
  "categoriaId": 3,
  "nombre": "Cinturón de Cuero Loewe",
  "descripcion": "Cinturón de piel de ternera plena flor. Hebilla de bronce con logo grabado.",
  "precio": 195.0,
  "stock": 8,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 206,
  "categoriaId": 2,
  "nombre": "ErgoChair Pro",
  "descripcion": "Silla ergonómica con soporte lumbar ajustable, reposacabezas 3D y malla transpirable.",
  "precio": 449.0,
  "stock": 8,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1561049501-e1f96bdd98fd?w=800",
  "modeloGlbUrl": "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 207,
  "categoriaId": 2,
  "nombre": "BenQ ScreenBar Plus",
  "descripcion": "Lámpara LED para monitor con pantalla táctil. Temperatura 2700-6500K.",
  "precio": 129.99,
  "stock": 15,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 208,
  "categoriaId": 2,
  "nombre": "DeLonghi Magnifica Evo",
  "descripcion": "Cafetera superautomática con molinillo integrado y sistema LatteCrema.",
  "precio": 599.0,
  "stock": 6,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 209,
  "categoriaId": 2,
  "nombre": "Dyson V15 Detect",
  "descripcion": "Aspirador inalámbrico con láser que ilumina el polvo. Hasta 60min autonomía.",
  "precio": 699.0,
  "stock": 9,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 210,
  "categoriaId": 2,
  "nombre": "Philips Hue Starter Kit",
  "descripcion": "3 bombillas LED inteligentes + bridge. 16 millones de colores, control por app.",
  "precio": 129.99,
  "stock": 20,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 211,
  "categoriaId": 2,
  "nombre": "IKEA KALLAX Estantería 4x4",
  "descripcion": "Estantería modular 147x147cm. Compatible con insertos y cajones KALLAX.",
  "precio": 119.99,
  "stock": 12,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 212,
  "categoriaId": 2,
  "nombre": "Weber Original Kettle 57cm",
  "descripcion": "Barbacoa de carbón clásica con tapa esmaltada. Parrilla de acero niquelado.",
  "precio": 189.0,
  "stock": 7,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 213,
  "categoriaId": 2,
  "nombre": "Ninja Foodi Smart XL Grill",
  "descripcion": "Plancha inteligente que regula temperatura automáticamente. 6 funciones.",
  "precio": 249.99,
  "stock": 11,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 214,
  "categoriaId": 2,
  "nombre": "Roomba j9+",
  "descripcion": "Robot aspirador con vaciado automático, mapeo inteligente y detección de obstáculos.",
  "precio": 899.0,
  "stock": 4,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 215,
  "categoriaId": 2,
  "nombre": "Colchón Emma Original King",
  "descripcion": "Colchón viscoelástico 5 capas. Firmeza media, certificado OEKO-TEX.",
  "precio": 649.0,
  "stock": 6,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 216,
  "categoriaId": 9,
  "nombre": "Scott Aspect 950 MTB",
  "descripcion": "Bicicleta de montaña hardtail. Cuadro aluminio, horquilla 100mm, Shimano 21v.",
  "precio": 699.0,
  "stock": 5,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 217,
  "categoriaId": 9,
  "nombre": "Manduka PRO Yoga Mat",
  "descripcion": "Esterilla profesional 6mm. Superficie antideslizante, libre de PVC, 180x61cm.",
  "precio": 120.0,
  "stock": 20,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 218,
  "categoriaId": 9,
  "nombre": "Garmin Fenix 7X Solar",
  "descripcion": "Smartwatch multideporte con carga solar. Mapas topográficos, GPS multiband.",
  "precio": 799.0,
  "stock": 7,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 219,
  "categoriaId": 9,
  "nombre": "Patagonia Torrentshell 3L",
  "descripcion": "Chubasquero ligero H2No 3 capas, 100% reciclado. Peso: 310g.",
  "precio": 179.0,
  "stock": 16,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1483478550801-ceba5fe50e8e?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 220,
  "categoriaId": 9,
  "nombre": "TRX Home 2 Suspension",
  "descripcion": "Sistema de entrenamiento en suspensión. Ancla para puerta incluida.",
  "precio": 199.99,
  "stock": 18,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 221,
  "categoriaId": 9,
  "nombre": "Deuter Speed Lite 20L",
  "descripcion": "Mochila ultraligera para senderismo. Ventilación Airstripes, materiales reciclados.",
  "precio": 89.99,
  "stock": 18,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 222,
  "categoriaId": 9,
  "nombre": "Speedo Fastskin LZR Pure",
  "descripcion": "Bañador de competición con tejido LZR X. Certificado FINA para competición.",
  "precio": 89.0,
  "stock": 14,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 223,
  "categoriaId": 9,
  "nombre": "Theragun Pro Gen 5",
  "descripcion": "Pistola de masaje percutivo profesional. 5 velocidades, 6 cabezales, app.",
  "precio": 399.0,
  "stock": 9,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 224,
  "categoriaId": 9,
  "nombre": "Bowflex SelectTech 552",
  "descripcion": "Mancuernas ajustables de 2.3 a 24kg. Sustituyen 15 pares de mancuernas.",
  "precio": 349.0,
  "stock": 8,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 225,
  "categoriaId": 9,
  "nombre": "Garmin Edge 1040 Solar",
  "descripcion": "Ciclocomputador GPS con carga solar. Mapas, rendimiento, conectividad Garmin.",
  "precio": 649.0,
  "stock": 6,
  "stockMinimo": 5,
  "imagenUrl": "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800",
  "modeloGlbUrl": "https://raw.githubusercontent.com/mohasb/modelia-assets/main/zNoCategory/NeilArmstrong.glb",
  "activo": true,
  "createdAt": "2026-04-18T13:59:55",
  "destacado": false
 },
 {
  "id": 226,
  "categoriaId": 1,
  "nombre": "Nuevo",
  "descripcion": "Nuevo",
  "precio": 1000.0,
  "stock": 25,
  "stockMinimo": 5,
  "imagenUrl": null,
  "modeloGlbUrl": null,
  "activo": false,
  "createdAt": "2026-04-19T12:34:42",
  "destacado": false
 }
]''';
